### ISSUE TITLE
Unable to load driver

### ISSUE THREAD

**Issue by tiba1987** [robertklep/node-kaku-rpi#2]
const KlikAanKlikUit = require('kaku-rpi');
let kaku = KlikAanKlikUit([12, 266, 7, 5]);

When I use the example code I get the following error:

..../rpio/lib/rpio.js:326
                        throw "Invalid pin";
                        ^
Invalid pin

What am I doing wrong??

**Comment by robertklep** [comment]
Sorry, the documentation is a bit unclear:
```
let kaku = KlikAanKlikUit([PIN, PERIODUSEC, REPEATS, PULSEWIDTH]);
```

This means that all arguments (inside the `[...]`) are optional. If you do add one (or more), it doesn't mean that the brackets should be included too.

So try this:
```
let kaku = KlikAanKlikUit(12, 266, 7, 5);
```

**Comment by tiba1987** [comment]
That fixed my problem. Thanks a lot!
