### ISSUE TITLE
Unable to install node-kaku-rpi: saveError ENOENT: no such file or directory, open '/home/pi/package.json'

### ISSUE THREAD

**Issue by ChielChiel** [robertklep/node-kaku-rpi#4]
Hi, I'm trying to install this package to check whether my Kaku APA3-1500R outlets are compatible with the homebridge plugin.

However when trying to install this package on my RPI 3b with:
``` bash
sudo npm i kaku-rpi --unsafe-perm
```
I get the following error:
``` bash
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ kaku-rpi@2.2.0
updated 1 package and audited 11 packages in 2.645s
found 0 vulnerabilities
```
Thus it seems that it cannot be installed for some reason. 
Which is confirmed when running `kaku D 1 1`:
`-bash: kaku: command not found`

How could I fix this?

**Comment by robertklep** [comment]
I don't see any real errors, and this line:
```
+ kaku-rpi@2.2.0
```
suggests that it got installed successfully.

However:
```
-bash: kaku: command not found
```
If you want to use the command line utility, you should install the package globally:
```
sudo npm i kaku-rpi -g --unsafe-perm
```
Otherwise you have to run it like this:
```
~/node_modules/.bin/kaku
```

**Comment by ChielChiel** [comment]
Thanks for the quick reply! 
I must have missed that.
